layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # github: aligorithm
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: aligorithm
  # mastodon: your_username
  medium: aligorithm
  stackoverflow: 11242221
  # telegram: your_username
  twitter: _aligorithm
  unsplash: aligorithm
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Flutter
    web_url: https://github.com/topics/flutter

  - name: Dart
    web_url: https://github.com/topics/dart

  - name: Android
    web_url: https://github.com/topics/android

  - name: PHP
    web_url: https://github.com/topics/php

  - name: Security
    web_url: https://github.com/topics/security

  - name: Kali-Linux
    web_url: https://github.com/topics/kali-linux

  - name: Arduino
    web_url: https://github.com/topics/arduino